# Import :- Importing libraries.

In [1]:
import numpy as np 
import pandas as pd

# pd.series :- covert list to 1D array.

In [2]:
"""Creating a Series by passing a list of values, letting pandas create a default integer index:"""
s = pd.Series([1, 3, 5, np.nan, 6, 8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

# pd.DataFrame :- Convert Dictionary into Dataframe.

In [3]:
"""Creating a DataFrame by passing a dictionary of objects that can be converted into a series-like structure"""
data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}
df = pd.DataFrame(data)
df

   calories  duration
0       420        50
1       380        40
2       390        45

# pd.read :- Import needed File.

In [4]:
"""Reading data files"""
df=pd.read_csv("../input/wine-reviews/winemag-data-130k-v2.csv")

# pd.read (index_col=0) :- Import needed File while coverting first column into index.

In [5]:
"""Reading data files and seting a column as index"""
df=pd.read_csv("../input/wine-reviews/winemag-data-130k-v2.csv",index_col=0)

# df.head() :- Getting first 5 values of df.

In [6]:
"""Getting first five values of dataset"""
df.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulk√† Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O‚ÄôKeefe,@kerinokeefe,Nicosia 2013 Vulk√† Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

# df.tail() :- Getting last 5 values of df.

In [7]:
"""Returns the headers and the last rows"""
df.tail()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Sp√§tlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben M√ºller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben M√ºller-Burggraef)
129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gew√ºrztraminer,Domaine Gresser
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuv√©e Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuv√©e Car...,Gew√ºrztraminer,Domaine Schoffit

# df.shape :- Getting Dimensions of df.

In [8]:
"""We can use the shape attribute to check how large the resulting DataFrame is"""
df.shape

(129971, 13)

# len(df) :- Getting legth (No. of content) of df.

In [9]:
"""Provides with the length of the DataFrame"""
len(df)

129971

# df.describe() :- To have a brief Description.

In [10]:
"""used to generate descriptive statistics of the data in a Pandas DataFrame or Series. It summarizes central tendency and dispersion of the dataset. """
df.describe()

              points          price
count  129971.000000  120975.000000
mean       88.447138      35.363389
std         3.039730      41.022218
min        80.000000       4.000000
25%        86.000000      17.000000
50%        88.000000      25.000000
75%        91.000000      42.000000
max       100.000000    3300.000000

# df.columns :- To get list of Columns.

In [11]:
"""see all the columns. using .columns function"""
df.columns

Index(['country', 'description', 'designation', 'points', 'price', 'province',
       'region_1', 'region_2', 'taster_name', 'taster_twitter_handle', 'title',
       'variety', 'winery'],
      dtype='object')

# df.info() :- To get brief info. about df. (Mainly null values.)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 129971 entries, 0 to 129970
Data columns (total 13 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   country                129908 non-null  object
 1   description            129971 non-null  object
 2   designation            92506 non-null   object
 3   points                 129971 non-null  int64
 4   price                  120975 non-null  float64
 5   province               129908 non-null  object
 6   region_1               108724 non-null  object
 7   region_2               50511 non-null   object
 8   taster_name            103727 non-null  object
 9   taster_twitter_handle  98758 non-null   object
 10  title                  129971 non-null  object
 11  variety                129970 non-null  object
 12  winery                 129971 non-null  object
dtypes: float64(1), int64(1), object(11)
memory usage: 13.9+ MB

# df.memory_usage() :- To get total memory being used by each column

In [13]:
"""memory_usage() returns a Pandas Series having the memory usage of each column (in bytes) in a Pandas DataFrame"""
df.memory_usage()

Index                    1039768
country                  1039768
description              1039768
designation              1039768
points                   1039768
price                    1039768
province                 1039768
region_1                 1039768
region_2                 1039768
taster_name              1039768
taster_twitter_handle    1039768
title                    1039768
variety                  1039768
winery                   1039768
dtype: int64

# .astype('') :- To cast particular column in particular format.

In [14]:
"""astype() is used to cast a Python object to a particular data type"""
df['price'] = df['price'].astype('object')

# .iloc[ ] (Slicing) - To get the specified no. of rows from df.

In [15]:
"""oc[:] helps to access a group of rows and columns in a dataset, a slice of the dataset, as per our requirement"""
df.loc[0:4]

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulk√† Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O‚ÄôKeefe,@kerinokeefe,Nicosia 2013 Vulk√† Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

# Slicing - To get the specified no. of rows from df including mentioned columns.
*** [] :- mentioned columns will be displayed only.**

In [16]:
"""oc[:] helps to access a group of rows and columns in a dataset, a slice of the dataset, as per our requirement"""
df.loc[0:4, ['country', 'points', 'variety']]

    country  points         variety
0     Italy      87     White Blend
1  Portugal      87  Portuguese Red
2        US      87      Pinot Gris
3        US      87        Riesling
4        US      87      Pinot Noir

In [17]:
# """to_datetime() converts a Python object to datetime format."""
# data_1['DOB'] = pd.to_datetime(data_1['DOB'])

# .value_count() :- Return a Series containing counts of unique values

In [18]:
"""value_counts() returns a Pandas Series containing the counts of unique values."""
df['country'].value_counts()

US                        54504
France                    22093
Italy                     19540
Spain                      6645
Portugal                   5691
Chile                      4472
Argentina                  3800
Austria                    3345
Australia                  2329
Germany                    2165
New Zealand                1419
South Africa               1401
Israel                      505
Greece                      466
Canada                      257
Hungary                     146
Bulgaria                    141
Romania                     120
Uruguay                     109
Turkey                       90
Slovenia                     87
Georgia                      86
England                      74
Croatia                      73
Mexico                       70
Moldova                      59
Brazil                       52
Lebanon                      35
Morocco                      28
Peru                         16
Ukraine                      14
Serbia                       12
Czech Republic               12
Macedonia                    12
Cyprus                       11
India                         9
Switzerland                   7
Luxembourg                    6
Bosnia and Herzegovina        2
Armenia                       2
Slovakia                      1
China                         1
Egypt                         1
Name: country, dtype: int64

# .drop_duplicates :- To remove rows with duplicate Values
*** (inplace=True) :- to replace new df wiht  old df**

In [19]:
"""drop_duplicates() returns a Pandas DataFrame with duplicate rows removed"""
df.drop_duplicates(inplace=True)

# df.groupby :- grouping the data according to the categories

In [20]:
"""groupby() is used to group a Pandas DataFrame by 1 or more columns, and perform some mathematical operation on it. """
df.groupby('country').points.mean()

country
Argentina                 86.649831
Armenia                   87.500000
Australia                 88.561220
Austria                   90.129532
Bosnia and Herzegovina    86.500000
Brazil                    84.632653
Bulgaria                  87.878788
Canada                    89.309735
Chile                     86.460564
China                     89.000000
Croatia                   87.185714
Cyprus                    87.100000
Czech Republic            87.090909
Egypt                     84.000000
England                   91.746032
France                    88.866752
Georgia                   87.605263
Germany                   89.895582
Greece                    87.238426
Hungary                   89.294574
India                     90.250000
Israel                    88.454936
Italy                     88.576198
Lebanon                   87.593750
Luxembourg                88.800000
Macedonia                 86.818182
Mexico                    85.161765
Moldova                   87.142857
Morocco                   88.708333
New Zealand               88.299687
Peru                      83.562500
Portugal                  88.263128
Romania                   86.313725
Serbia                    87.625000
Slovakia                  87.000000
Slovenia                  88.129870
South Africa              88.033820
Spain                     87.235612
Switzerland               88.500000
Turkey                    88.074074
US                        88.555384
Ukraine                   84.071429
Uruguay                   86.663265
Name: points, dtype: float64

# df.merge :- to merge two different df.
*** (on='') :- to Merge on specified column name**

In [21]:
# """merge() is used to merge 2 Pandas DataFrame"""
# data_1.merge(data_2, on='Name', how='left')

# df.sort_values :- To sort values of mentioned Column
*** (inplace=True) :- To replace df.**
*** (ascending=False) :- To specify the order of sorting.**

In [22]:
"""sort_values() is used to sort column in a Pandas DataFrame (or a Pandas Series) by values in ascending or descending order."""
df.sort_values(by='country', inplace=True)
df.sort_values(by='country', inplace=True,ascending=False)

# fillna :- TO fill NAN vlaues in df.
*** ffill :- to fill forward values of NAN cell.**
*** bfill :- to fill backward values of NAN cell.**

In [23]:
"""fillna() helps to replace all NaN values in a DataFrame or Series by imputing these missing values with more appropriate values."""
df['price'].fillna(38.5, inplace=True)
df['price'].fillna(df['price'].mean(), inplace=True)
df['price'].fillna(df['price'].median(), inplace=True)
df['price'].fillna(df['price'].mode(), inplace=True)
df['designation'].ffill(axis=0,inplace=True)
df['designation'].bfill(axis=0,inplace=True)

# df.drop() :- to drop specified columns.

In [24]:
"""drop some unnecessary columns using df.drop()"""
df = df.drop(columns=['region_2', 'region_1'])

# .iloc[ ] (Slicing) - To get the specified no. of rows from df.

In [25]:
"""This function takes as a parameter the rows and column indices and gives you the subset of the DataFrame accordingly."""
df.iloc[:10, 5:10]

,province,taster_name,taster_twitter_handle,title,variety
19512,Canelones,Michael Schachner,@wineschach,Marichal 2013 Grand Reserve A Tannat (Canelones),Tannat
55673,Atlantida,Michael Schachner,@wineschach,Bracco Bosca 2016 Omb√∫ Reserve Tannat (Atlantida),Tannat
25497,Uruguay,Michael Schachner,@wineschach,Alto de la Ballena 2011 Reserve Tannat-Viognie...,Red Blend
48301,Canelones,Michael Schachner,@wineschach,Gimenez Mendez 2007 Identity Red (Canelones),Red Blend
124223,Canelones,Michael Schachner,@wineschach,Marichal 2011 Premium Varietal Merlot (Canelones),Merlot
39361,Uruguay,Michael Schachner,@wineschach,Narbona NV Blend 002 Limited Edition Tannat-Ca...,Tannat-Cabernet Franc
14722,Juanico,Michael Schachner,@wineschach,Familia Deicas 2008 Don Pascual Reserve Tannat...,Tannat
25485,Canelones,Michael Schachner,@wineschach,Familia Deicas 2015 Domaine Castelar Vineyard ...,Tannat
14723,San Jose,Michael Schachner,@wineschach,Castillo Viejo 2007 Parcela Vieja Cabernet Fra...,Cabernet Franc
37960,Uruguay,Michael Schachner,@wineschach,Garz√≥n 2014 Varietales Albari√±o (Uruguay),Albari√±o

# df.query() :- To filter or to ask if True or False

In [26]:
"""You can filter or query using a boolean expression"""
df.query("points > price")

,country,description,designation,points,price,province,taster_name,taster_twitter_handle,title,variety,winery
19512,Uruguay,"A lot has been thrown at this Tannat, and thus...",Grand Reserve A,84,65.0,Canelones,Michael Schachner,@wineschach,Marichal 2013 Grand Reserve A Tannat (Canelones),Tannat,Marichal
55673,Uruguay,Oaky spice aromas are up front on a nose that ...,Omb√∫ Reserve,88,21.0,Atlantida,Michael Schachner,@wineschach,Bracco Bosca 2016 Omb√∫ Reserve Tannat (Atlantida),Tannat,Bracco Bosca
25497,Uruguay,This Tannat (with 15% Viognier) is full and oa...,Reserve Tannat-Viognier,88,19.0,Uruguay,Michael Schachner,@wineschach,Alto de la Ballena 2011 Reserve Tannat-Viognie...,Red Blend,Alto de la Ballena
48301,Uruguay,"Dark, roasted and smelling of licorice, root b...",Identity,85,20.0,Canelones,Michael Schachner,@wineschach,Gimenez Mendez 2007 Identity Red (Canelones),Red Blend,Gimenez Mendez
124223,Uruguay,"While this smells a bit rough and herbal, it's...",Premium Varietal,84,16.0,Canelones,Michael Schachner,@wineschach,Marichal 2011 Premium Varietal Merlot (Canelones),Merlot,Marichal
...,...,...,...,...,...,...,...,...,...,...,...
124176,NaN,This Swiss red blend is composed of four varie...,Les Romaines,90,30.0,NaN,Jeff Jenssen,@worldwineguys,Les Fr√®res Dutruy 2014 Les Romaines Red,Red Blend,Les Fr√®res Dutruy
129407,NaN,Dry spicy aromas of dusty plum and tomato add ...,Reserve,89,22.0,NaN,Michael Schachner,@wineschach,El Capricho 2015 Reserve Cabernet Sauvignon,Cabernet Sauvignon,El Capricho
129408,NaN,El Capricho is one of Uruguay's more consisten...,Reserve,89,22.0,NaN,Michael Schachner,@wineschach,El Capricho 2015 Reserve Tempranillo,Tempranillo,El Capricho
129590,NaN,"A blend of 60% Syrah, 30% Cabernet Sauvignon a...",Shah,90,30.0,NaN,Mike DeSimone,@worldwineguys,B√ºy√ºl√ºbaƒü 2012 Shah Red,Red Blend,B√ºy√ºl√ºbaƒü
129900,NaN,This wine offers a delightful bouquet of black...,Shah,91,32.0,NaN,Mike DeSimone,@worldwineguys,Psagot 2014 Merlot,Merlot,Psagot

# df.select_dtypes() :- To select the specified Datatype columns only.

In [27]:
"""Getting only categorical columns in a dataset"""
df.select_dtypes(include=object)

,country,description,designation,province,taster_name,taster_twitter_handle,title,variety,winery
19512,Uruguay,"A lot has been thrown at this Tannat, and thus...",Grand Reserve A,Canelones,Michael Schachner,@wineschach,Marichal 2013 Grand Reserve A Tannat (Canelones),Tannat,Marichal
55673,Uruguay,Oaky spice aromas are up front on a nose that ...,Omb√∫ Reserve,Atlantida,Michael Schachner,@wineschach,Bracco Bosca 2016 Omb√∫ Reserve Tannat (Atlantida),Tannat,Bracco Bosca
25497,Uruguay,This Tannat (with 15% Viognier) is full and oa...,Reserve Tannat-Viognier,Uruguay,Michael Schachner,@wineschach,Alto de la Ballena 2011 Reserve Tannat-Viognie...,Red Blend,Alto de la Ballena
48301,Uruguay,"Dark, roasted and smelling of licorice, root b...",Identity,Canelones,Michael Schachner,@wineschach,Gimenez Mendez 2007 Identity Red (Canelones),Red Blend,Gimenez Mendez
124223,Uruguay,"While this smells a bit rough and herbal, it's...",Premium Varietal,Canelones,Michael Schachner,@wineschach,Marichal 2011 Premium Varietal Merlot (Canelones),Merlot,Marichal
...,...,...,...,...,...,...,...,...,...
124176,NaN,This Swiss red blend is composed of four varie...,Les Romaines,NaN,Jeff Jenssen,@worldwineguys,Les Fr√®res Dutruy 2014 Les Romaines Red,Red Blend,Les Fr√®res Dutruy
129407,NaN,Dry spicy aromas of dusty plum and tomato add ...,Reserve,NaN,Michael Schachner,@wineschach,El Capricho 2015 Reserve Cabernet Sauvignon,Cabernet Sauvignon,El Capricho
129408,NaN,El Capricho is one of Uruguay's more consisten...,Reserve,NaN,Michael Schachner,@wineschach,El Capricho 2015 Reserve Tempranillo,Tempranillo,El Capricho
129590,NaN,"A blend of 60% Syrah, 30% Cabernet Sauvignon a...",Shah,NaN,Mike DeSimone,@worldwineguys,B√ºy√ºl√ºbaƒü 2012 Shah Red,Red Blend,B√ºy√ºl√ºbaƒü
129900,NaN,This wine offers a delightful bouquet of black...,Shah,NaN,Mike DeSimone,@worldwineguys,Psagot 2014 Merlot,Merlot,Psagot

In [28]:
"""Incase of all numeric values we will add mean in place of null values"""
num=df.select_dtypes(exclude=object)
num

        points  price
19512       84   65.0
55673       88   21.0
25497       88   19.0
48301       85   20.0
124223      84   16.0
...        ...    ...
124176      90   30.0
129407      89   22.0
129408      89   22.0
129590      90   30.0
129900      91   32.0

[119988 rows x 2 columns]

# df().dtypes :- To find the datatype of mentioned column.

In [29]:
"""know the data types of the variables """
df['description'].dtypes

dtype('O')

# np.random.randint() :- To receive random integers of mentioned length.

In [30]:
"""it inserts a column in the specified position"""
random_col = np.random.randint(100, size=len(df))
df.insert(3, 'random_col', random_col)

# df.cumsum() :- To get the commulative sumation of given column.

In [31]:
df[['points', 'price']].cumsum()

          points      price
19512         84       65.0
55673        172       86.0
25497        260      105.0
48301        345      125.0
124223       429      141.0
...          ...        ...
124176  10611648  4298127.5
129407  10611737  4298149.5
129408  10611826  4298171.5
129590  10611916  4298201.5
129900  10612007  4298233.5

[119988 rows x 2 columns]

# df.sample() :- To receive the rondom sample rows and columns from df.

In [32]:
"""When the size of the dataset is too big, you can take a representative sample from it to perform the analysis and predictive modeling."""
df.sample(n = 200)
df.sample(frac = 0.25)

,country,description,designation,random_col,points,price,province,taster_name,taster_twitter_handle,title,variety,winery
81469,US,"This winery's Pinots rarely rise to the top, b...",Special Reserve,80,89,35.0,California,NaN,NaN,Domaine Chandon 2005 Pinot Noir (Carneros),Pinot Noir,Domaine Chandon
51803,US,"Soft baking-spice notes mesh with vanilla, red...",LPF,3,86,15.0,California,Matt Kettmann,@mattkettmann,Blackburn Wine Company 2014 Cabernet Sauvignon...,Cabernet Sauvignon,Blackburn Wine Company
117407,US,You never quite know what you're getting with ...,Camp Meeting Ridge Estate Vineyard,1,88,35.0,California,NaN,NaN,Imagery 2008 Barbera (Sonoma County),Barbera,Imagery
11894,France,This single-vineyard wine is rich and crisply ...,Les Plant√©s,2,90,19.0,Burgundy,Roger Voss,@vossroger,Vignerons des Terres Secr√®tes 2014 Les Plant√©s...,Chardonnay,Vignerons des Terres Secr√®tes
14466,France,"Tannat and Pinenc, both native to this region ...",L'Empreinte de Saint-Mont,81,91,18.0,Southwest France,Roger Voss,@vossroger,Producteurs Plaimont 2010 L'Empreinte de Saint...,Red Blend,Producteurs Plaimont
...,...,...,...,...,...,...,...,...,...,...,...,...
76681,Portugal,"This is a fun, candy-pink colored wine that is...",Vera,8,84,12.0,Vinho Verde,Roger Voss,@vossroger,Obrigado 2014 Vera Ros√© (Vinho Verde),Portuguese Ros√©,Obrigado
91211,US,It was difficult to get much out of the glass;...,Estate Grown,39,86,22.0,Washington,Paul Gregutt,@paulgwine,Seven Hills 2009 Merlot (Columbia Valley (WA)),Merlot,Seven Hills
58838,US,This wine over-delivers in quality for the pri...,Sluice Box,91,91,28.0,California,Virginie Boone,@vboone,B Side 2013 Cabernet Sauvignon (Napa Valley),Cabernet Sauvignon,B Side
51938,France,"A blend of Riesling, Pinot Gris, Gewurztramine...",Cuv√©e 8,59,92,35.0,Alsace,Roger Voss,@vossroger,Domaine Pfister 2010 Cuv√©e 8 White (Alsace),White Blend,Domaine Pfister
113007,France,The Haut-Brion winemaking team produces this r...,Ch√¢teau la Perri√®re,45,86,38.5,Bordeaux,Roger Voss,@vossroger,Clarendelle 2009 Bordeaux,Bordeaux-style Red Blend,Clarendelle

In [33]:
"""This function helps you query a dataset based on a boolean condition"""
df['random_col'].where(df['random_col'] > 50)
df['random_col'].where(df['random_col'] > 50, 0)

19512      0
55673     80
25497     84
48301      0
124223    80
          ..
124176     0
129407    79
129408    53
129590    77
129900     0
Name: random_col, Length: 119988, dtype: int64

# df.unique() :- To find the unique values of specified Column.

In [34]:
"""It is used to find out the unique values of a categorical column."""
df['country'].unique()

array(['Uruguay', 'Ukraine', 'US', 'Turkey', 'Switzerland', 'Spain',
       'South Africa', 'Slovenia', 'Slovakia', 'Serbia', 'Romania',
       'Portugal', 'Peru', 'New Zealand', 'Morocco', 'Moldova', 'Mexico',
       'Macedonia', 'Luxembourg', 'Lebanon', 'Italy', 'Israel', 'India',
       'Hungary', 'Greece', 'Germany', 'Georgia', 'France', 'England',
       'Egypt', 'Czech Republic', 'Cyprus', 'Croatia', 'China', 'Chile',
       'Canada', 'Bulgaria', 'Brazil', 'Bosnia and Herzegovina',
       'Austria', 'Australia', 'Armenia', 'Argentina', nan], dtype=object)

In [35]:
"""This function lets you know how many unique values do you have in a column"""
df['province'].nunique()

425

# df.isin() :- To check if the column actually contains the specified values.

In [36]:
"""This function checks returns the values in that dataset """
nationality = ["Argentina", "England"]
df[df.country.isin(nationality)]

,country,description,designation,random_col,points,price,province,taster_name,taster_twitter_handle,title,variety,winery
72070,England,"A fragrant, sherbety cloud of spring meadow an...",Blanc de Blancs Brut,97,91,50.0,England,Anne Krebiehl¬†MW,@AnneInVino,Bolney Wine Estate 2015 Blanc de Blancs Brut C...,Chardonnay,Bolney Wine Estate
72824,England,A haze of summer flowers hovers across a fizzy...,Cavendish,33,89,39.0,England,Anne Krebiehl¬†MW,@AnneInVino,Ridgeview Estate 2013 Cavendish Sparkling (Eng...,Sparkling Blend,Ridgeview Estate
56417,England,Notes of apple immediately rise from the glass...,Classic Cuv√©e,51,91,50.0,England,Anne Krebiehl¬†MW,@AnneInVino,Hoffmann & Rathbone 2013 Classic Cuv√©e Sparkli...,Sparkling Blend,Hoffmann & Rathbone
60002,England,Beautifully delineated fruit constitues the no...,The Trouble with Dreams,12,95,80.0,England,Anne Krebiehl¬†MW,@AnneInVino,Sugrue Pierre Ltd. 2010 The Trouble with Dream...,Sparkling Blend,Sugrue Pierre Ltd.
27356,England,Freshly cut peel of tart but ripe red apple en...,Brut Ros√©,22,93,80.0,England,Anne Krebiehl¬†MW,@AnneInVino,Gusbourne Estate 2013 Brut Ros√© Pinot Noir (En...,Pinot Noir,Gusbourne Estate
...,...,...,...,...,...,...,...,...,...,...,...,...
47523,Argentina,"Tapiz's best wine to date, and the first one t...",Selecci√≥n de Barricas Reserva,54,93,35.0,Mendoza Province,Michael Schachner,@wineschach,Tapiz 2007 Selecci√≥n de Barricas Reserva Red (...,Red Blend,Tapiz
127975,Argentina,"Murky, earthy aromas of plum and red berry fee...",De Sangre,21,87,27.0,Mendoza Province,Michael Schachner,@wineschach,Luigi Bosca 2013 De Sangre Red (Mendoza),Cabernet Blend,Luigi Bosca
81893,Argentina,"Ripe and saturated on the nose, this big boy i...",De Sangre,34,89,20.0,Mendoza Province,Michael Schachner,@wineschach,Tiza 2012 Malbec (Uco Valley),Malbec,Tiza
21420,Argentina,"Amancaya, a blend of Malbec and Cabernet Sauvi...",Amancaya,79,90,19.0,Mendoza Province,Michael Schachner,@wineschach,Bodegas Caro 2006 Amancaya Malbec-Cabernet Sau...,Malbec-Cabernet Sauvignon,Bodegas Caro
24050,Argentina,"Big, bulky and granular, with high alcohol and...",Reserve,16,85,20.0,Mendoza Province,Michael Schachner,@wineschach,Andeluna 2006 Reserve Cabernet Sauvignon (Tupu...,Cabernet Sauvignon,Andeluna

# df.replace() :- To replace mentioned values with new value.

In [37]:
""" When we need to replace only one unique value of a column """
df.replace("India", "INDIA")

,country,description,designation,random_col,points,price,province,taster_name,taster_twitter_handle,title,variety,winery
19512,Uruguay,"A lot has been thrown at this Tannat, and thus...",Grand Reserve A,27,84,65.0,Canelones,Michael Schachner,@wineschach,Marichal 2013 Grand Reserve A Tannat (Canelones),Tannat,Marichal
55673,Uruguay,Oaky spice aromas are up front on a nose that ...,Omb√∫ Reserve,80,88,21.0,Atlantida,Michael Schachner,@wineschach,Bracco Bosca 2016 Omb√∫ Reserve Tannat (Atlantida),Tannat,Bracco Bosca
25497,Uruguay,This Tannat (with 15% Viognier) is full and oa...,Reserve Tannat-Viognier,84,88,19.0,Uruguay,Michael Schachner,@wineschach,Alto de la Ballena 2011 Reserve Tannat-Viognie...,Red Blend,Alto de la Ballena
48301,Uruguay,"Dark, roasted and smelling of licorice, root b...",Identity,24,85,20.0,Canelones,Michael Schachner,@wineschach,Gimenez Mendez 2007 Identity Red (Canelones),Red Blend,Gimenez Mendez
124223,Uruguay,"While this smells a bit rough and herbal, it's...",Premium Varietal,80,84,16.0,Canelones,Michael Schachner,@wineschach,Marichal 2011 Premium Varietal Merlot (Canelones),Merlot,Marichal
...,...,...,...,...,...,...,...,...,...,...,...,...
124176,NaN,This Swiss red blend is composed of four varie...,Les Romaines,48,90,30.0,NaN,Jeff Jenssen,@worldwineguys,Les Fr√®res Dutruy 2014 Les Romaines Red,Red Blend,Les Fr√®res Dutruy
129407,NaN,Dry spicy aromas of dusty plum and tomato add ...,Reserve,79,89,22.0,NaN,Michael Schachner,@wineschach,El Capricho 2015 Reserve Cabernet Sauvignon,Cabernet Sauvignon,El Capricho
129408,NaN,El Capricho is one of Uruguay's more consisten...,Reserve,53,89,22.0,NaN,Michael Schachner,@wineschach,El Capricho 2015 Reserve Tempranillo,Tempranillo,El Capricho
129590,NaN,"A blend of 60% Syrah, 30% Cabernet Sauvignon a...",Shah,77,90,30.0,NaN,Mike DeSimone,@worldwineguys,B√ºy√ºl√ºbaƒü 2012 Shah Red,Red Blend,B√ºy√ºl√ºbaƒü
129900,NaN,This wine offers a delightful bouquet of black...,Shah,39,91,32.0,NaN,Mike DeSimone,@worldwineguys,Psagot 2014 Merlot,Merlot,Psagot

# df.rename() :- To replce name of columns with new one.

In [38]:
"""It is used to rename the column/s."""
df.rename(columns = {"country": "Country", "price": "Price"})

,Country,description,designation,random_col,points,Price,province,taster_name,taster_twitter_handle,title,variety,winery
19512,Uruguay,"A lot has been thrown at this Tannat, and thus...",Grand Reserve A,27,84,65.0,Canelones,Michael Schachner,@wineschach,Marichal 2013 Grand Reserve A Tannat (Canelones),Tannat,Marichal
55673,Uruguay,Oaky spice aromas are up front on a nose that ...,Omb√∫ Reserve,80,88,21.0,Atlantida,Michael Schachner,@wineschach,Bracco Bosca 2016 Omb√∫ Reserve Tannat (Atlantida),Tannat,Bracco Bosca
25497,Uruguay,This Tannat (with 15% Viognier) is full and oa...,Reserve Tannat-Viognier,84,88,19.0,Uruguay,Michael Schachner,@wineschach,Alto de la Ballena 2011 Reserve Tannat-Viognie...,Red Blend,Alto de la Ballena
48301,Uruguay,"Dark, roasted and smelling of licorice, root b...",Identity,24,85,20.0,Canelones,Michael Schachner,@wineschach,Gimenez Mendez 2007 Identity Red (Canelones),Red Blend,Gimenez Mendez
124223,Uruguay,"While this smells a bit rough and herbal, it's...",Premium Varietal,80,84,16.0,Canelones,Michael Schachner,@wineschach,Marichal 2011 Premium Varietal Merlot (Canelones),Merlot,Marichal
...,...,...,...,...,...,...,...,...,...,...,...,...
124176,NaN,This Swiss red blend is composed of four varie...,Les Romaines,48,90,30.0,NaN,Jeff Jenssen,@worldwineguys,Les Fr√®res Dutruy 2014 Les Romaines Red,Red Blend,Les Fr√®res Dutruy
129407,NaN,Dry spicy aromas of dusty plum and tomato add ...,Reserve,79,89,22.0,NaN,Michael Schachner,@wineschach,El Capricho 2015 Reserve Cabernet Sauvignon,Cabernet Sauvignon,El Capricho
129408,NaN,El Capricho is one of Uruguay's more consisten...,Reserve,53,89,22.0,NaN,Michael Schachner,@wineschach,El Capricho 2015 Reserve Tempranillo,Tempranillo,El Capricho
129590,NaN,"A blend of 60% Syrah, 30% Cabernet Sauvignon a...",Shah,77,90,30.0,NaN,Mike DeSimone,@worldwineguys,B√ºy√ºl√ºbaƒü 2012 Shah Red,Red Blend,B√ºy√ºl√ºbaƒü
129900,NaN,This wine offers a delightful bouquet of black...,Shah,39,91,32.0,NaN,Mike DeSimone,@worldwineguys,Psagot 2014 Merlot,Merlot,Psagot

In [39]:
"""It provides you the number of data in the DataFrame in the specified direction"""
df.count(0)

country                  119929
description              119988
designation              119988
random_col               119988
points                   119988
price                    119988
province                 119929
taster_name               95071
taster_twitter_handle     90542
title                    119988
variety                  119987
winery                   119988
dtype: int64

In [40]:
df.columns

Index(['country', 'description', 'designation', 'random_col', 'points',
       'price', 'province', 'taster_name', 'taster_twitter_handle', 'title',
       'variety', 'winery'],
      dtype='object')

# pd.crosstab() :- used to compute a simple cross tabulation of two (or more) factors.

In [41]:
"""It gives you a frequency table that is a cross-tabulation of two variables"""
pd.crosstab(df['country'], df['variety'])

variety,Abouriou,Agiorgitiko,Aglianico,Aidani,Airen,Albana,Albanello,Albari√±o,Albarossa,Aleatico,...,Yapincak,Zelen,Zibibbo,Zierfandler,Zierfandler-Rotgipfler,Zinfandel,Zlahtina,Zweigelt,√áalkarasƒ±,≈Ωilavka
country,,,,,,,,,,,,,,,,,,,,,
Argentina,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Armenia,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Australia,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,3,0,0,0,0
Austria,0,0,0,0,0,0,0,0,0,0,...,0,0,0,14,5,0,0,174,0,0
Bosnia and Herzegovina,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Brazil,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Bulgaria,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Canada,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Chile,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
China,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Croatia,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,2,1,0,0
Cyprus,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Czech Republic,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Egypt,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
England,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
France,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Georgia,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Germany,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Greece,0,56,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Hungary,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
India,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Israel,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Italy,0,0,324,0,0,21,1,0,1,5,...,0,0,28,0,0,0,0,0,0,0
Lebanon,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Luxembourg,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Macedonia,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
Mexico,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Moldova,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Morocco,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
New Zealand,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Peru,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Portugal,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Romania,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Serbia,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Slovakia,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Slovenia,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
South Africa,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Spain,0,0,0,0,3,0,0,311,0,0,...,0,0,0,0,0,0,0,0,0,0
Switzerland,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Turkey,0,0,0,0,0,0,0,0,0,0,...,2,0,0,0,0,0,0,0,2,0
US,1,0,15,0,0,0,0,117,0,0,...,0,0,0,0,0,2527,0,7,0,0
Ukraine,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Uruguay,0,0,0,0,0,0,0,6,0,0,...,0,0,0,0,0,0,0,0,0,0

# df.sum() :- To display the summation of specified Columns.

In [42]:
"""The sum() method adds all values in each column and returns the sum for each column."""
df['price'].sum(axis=0)

4298233.5

# df.corr() :- To check co-relation between each value in df.

In [43]:
"""The corr() method calculates the relationship between each column in your data set."""
df.corr()

            random_col    points     price
random_col    1.000000  0.005317  0.000979
points        0.005317  1.000000  0.402995
price         0.000979  0.402995  1.000000

In [44]:
# """Update the DataFrame with the data from another DataFrame"""
# df1.update(df2)

In [45]:
# """Remove the rows before position 3 and after position 5 of the DataFrame:"""
# newdf = df.truncate(before=3, after=5)

In [46]:
"""Convert the columns into rows and vice versa:"""
newdf = df.T

In [47]:
"""Sort the DataFrame by index labels:"""
newdf = df.sort_index()

# df.round() :- to round off the value.

In [48]:
"""Round each number in the DataFrame into 1 decimal numbers:"""
df['price'].round(1)

19512     65.0
55673     21.0
25497     19.0
48301     20.0
124223    16.0
          ...
124176    30.0
129407    22.0
129408    22.0
129590    30.0
129900    32.0
Name: price, Length: 119988, dtype: float64

In [49]:
df.columns

Index(['country', 'description', 'designation', 'random_col', 'points',
       'price', 'province', 'taster_name', 'taster_twitter_handle', 'title',
       'variety', 'winery'],
      dtype='object')

# df.pivot_table() :- To plot pivot table to summarize the numeric value related to two different categories

In [50]:
"""Create a spreadsheet pivot table as a DataFrame"""
df.pivot_table(values="price",index="country",columns="variety")

variety,Abouriou,Agiorgitiko,Aglianico,Aidani,Airen,Albana,Albanello,Albari√±o,Albarossa,Aleatico,...,Yapincak,Zelen,Zibibbo,Zierfandler,Zierfandler-Rotgipfler,Zinfandel,Zlahtina,Zweigelt,√áalkarasƒ±,≈Ωilavka
country,,,,,,,,,,,,,,,,,,,,,
Argentina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Armenia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Australia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,29.333333,NaN,NaN,NaN,NaN
Austria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,33.678571,26.7,NaN,NaN,23.609195,NaN,NaN
Bosnia and Herzegovina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Brazil,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Bulgaria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Canada,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Chile,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
China,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Croatia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,14.5,25.000000,NaN,NaN
Cyprus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Czech Republic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Egypt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
England,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
France,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Georgia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Germany,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Greece,NaN,23.767857,NaN,27.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Hungary,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
India,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Israel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Italy,NaN,NaN,39.637346,NaN,NaN,26.02381,20.0,NaN,40.0,39.5,...,NaN,NaN,37.767857,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Lebanon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Luxembourg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Macedonia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.0
Mexico,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Moldova,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Morocco,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
New Zealand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Peru,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Portugal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Romania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Serbia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Slovakia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Slovenia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,38.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
South Africa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Spain,NaN,NaN,NaN,NaN,9.0,NaN,NaN,20.776527,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Switzerland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Turkey,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,18.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.0,NaN
US,75.0,NaN,31.466667,NaN,NaN,NaN,NaN,22.970085,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,29.439652,NaN,27.857143,NaN,NaN
Ukraine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Uruguay,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.333333,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# .max() :- To get maximum available value.

In [51]:
"""Return the highest value for each column:"""
df['price'].max()

3300.0

# .min() :- To get minimum available value.

In [52]:
"""Return the lowest value for each column:"""
df['price'].min()

4.0

In [53]:
# """Add the content of one DataFrame to another:"""
# newdf = df1.join(df2)

In [54]:
"""Merge DataFrame or named Series objects with a database-style join."""
df1 = pd.DataFrame({'lkey': ['foo', 'bar', 'baz', 'foo'],
                    'value': [1, 2, 3, 5]})
df2 = pd.DataFrame({'rkey': ['foo', 'bar', 'baz', 'foo'],
                    'value': [5, 6, 7, 8]})
df1.merge(df2, left_on='lkey', right_on='rkey')

  lkey  value_x rkey  value_y
0  foo        1  foo        5
1  foo        1  foo        8
2  foo        5  foo        5
3  foo        5  foo        8
4  bar        2  bar        6
5  baz        3  baz        7

# pd.get_dummies :- To convert categorical variable into numerical indicators.

In [55]:
"""Convert categorical variable into dummy/indicator variables."""
s = pd.Series(list('pqrp'))
pd.get_dummies(s)

   p  q  r
0  1  0  0
1  0  1  0
2  0  0  1
3  1  0  0

# pd.concate() :- To add multiple columns wrt axis.

In [56]:
"""pandas.concat() function does all the heavy lifting of performing concatenation operations along with an axis"""
# creating the Series
series1 = pd.Series([1, 2, 3])
display('series1:', series1)
series2 = pd.Series(['A', 'B', 'C'])
display('series2:', series2)
  
# concatenating
display('After concatenating:')
display(pd.concat([series1, series2]))

'series1:'

0    1
1    2
2    3
dtype: int64

'series2:'

0    A
1    B
2    C
dtype: object

'After concatenating:'

0    1
1    2
2    3
0    A
1    B
2    C
dtype: object

# lambda :- a small anonymous function that can take any number of arguments and execute an expression.

In [57]:
"""Lambda function"""
# creating and initializing a nested list
values_list = [[15, 2.5, 100], [20, 4.5, 50], [25, 5.2, 80],
               [45, 5.8, 48], [40, 6.3, 70], [41, 6.4, 90],
               [51, 2.3, 111]]
 
# creating a pandas dataframe
df = pd.DataFrame(values_list, columns=['Field_1', 'Field_2', 'Field_3'])
 
# Applying lambda function to find
# the product of 3 columns using
# df.assign()
df = df.assign(Product=lambda x: (x['Field_1'] * x['Field_2'] * x['Field_3']))

# pd.map :- substitute each value in a Series with another value.

In [58]:
"""pandas.map() is used to map values from two series having one column same. """
pokemon_names = pd.read_csv("../input/wine-reviews/winemag-data-130k-v2.csv", usecols = ["country"],squeeze = True)
  
#usecol is used to use selected columns
#index_col is used to make passed column as index
# pokemon_types = pd.read_csv("pokemon.csv", index_col = "Pokemon",squeeze = True)
  
#using pandas map function
# new=pokemon_names.map(pokemon_types)